export const ADD_PRODUCT = 'PRODUCT/ADD_PRODUCT';
export const EDIT_PRODUCT = 'PRODUCT/EDIT_PRODUCT';
export const REMOVE_PRODUCT = 'PRODUCT/REMOVE_PRODUCT';
export const VIEW_PRODUCT = 'PRODUCT/VIEW_PRODUCT';
